# Generated by Django 3.2.18 on 2023-05-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.cartitem', verbose_name='Продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'CartItemOrder',
                'verbose_name_plural': 'CartItemsOrders',
                'db_table': 'cart_items_orders',
            },
        ),
    ]
